# Generated by Django 4.0.3 on 2022-04-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('dis', models.CharField(max_length=250)),
                ('is_completed', models.BooleanField()),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
